CREATE TABLE favorites (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    u_id INTEGER NOT NULL,
    t_id INTEGER NOT NULL,
    created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY(t_id) REFERENCES travel_data(id) ON DELETE CASCADE,
    FOREIGN KEY(u_id) REFERENCES users_table(id) ON DELETE CASCADE
);